# -*- coding: utf-8 -*-
"""Factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xANzmUBJoASGYTKJiSFcdi3ZLsgehBXi
"""

n = int(input("Enter a number: "))

fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)

